{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "20a080fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Successfully created db engine.\n"
     ]
    }
   ],
   "source": [
    "#Imports\n",
    "import sys\n",
    "import json\n",
    "import csv\n",
    "import yaml\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib as mpl\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "import time\n",
    "from datetime import datetime\n",
    "import pprint\n",
    "import psycopg2\n",
    "from sqlalchemy import create_engine, text as sql_text\n",
    "#Import Util\n",
    "sys.path.append('benchmarking/')\n",
    "import util\n",
    "\n",
    "#LOAD ENVIRONMENT VARIABLES\n",
    "dotenv_path = 'variables.env'\n",
    "load_dotenv(dotenv_path=dotenv_path)\n",
    "\n",
    "schema = os.getenv('DISC_6_SCHEMA')\n",
    "port = os.getenv('DISC_6_PORT')\n",
    "host = os.getenv('DISC_6_HOST')\n",
    "database = os.getenv('DISC_6_DB')\n",
    "password = os.getenv('DISC_6_PASSWORD')\n",
    "connection = os.getenv('DISC_6_CONNECTION')\n",
    "\n",
    "#CREATE ENGINE\n",
    "db_eng = create_engine(f\"postgresql+psycopg2://{connection}:{password}@{host}:{port}/{database}\",\n",
    "                       connect_args={'options': '-csearch_path={}'.format(schema)},\n",
    "                       isolation_level = 'SERIALIZABLE')\n",
    "\n",
    "print(\"Successfully created db engine.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2a380945",
   "metadata": {},
   "outputs": [
    {
     "ename": "ProgrammingError",
     "evalue": "(psycopg2.errors.DuplicateColumn) column \"datetime\" of relation \"reviews\" already exists\n\n[SQL: \n alter table reviews\n     add column datetime timestamp;\n     \n]\n(Background on this error at: https://sqlalche.me/e/14/f405)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mDuplicateColumn\u001b[0m                           Traceback (most recent call last)",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1818\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> 1819\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdialect\u001b[38;5;241m.\u001b[39mdo_execute(\n\u001b[1;32m   1820\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   1821\u001b[0m         )\n\u001b[1;32m   1823\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_has_events \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mengine\u001b[38;5;241m.\u001b[39m_has_events:\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    731\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdo_execute\u001b[39m(\u001b[38;5;28mself\u001b[39m, cursor, statement, parameters, context\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[0;32m--> 732\u001b[0m     cursor\u001b[38;5;241m.\u001b[39mexecute(statement, parameters)\n",
      "\u001b[0;31mDuplicateColumn\u001b[0m: column \"datetime\" of relation \"reviews\" already exists\n",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[0;31mProgrammingError\u001b[0m                          Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 11\u001b[0m\n\u001b[1;32m      7\u001b[0m qimport \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\"\"\u001b[39m\u001b[38;5;124mupdate reviews\u001b[39m\n\u001b[1;32m      8\u001b[0m \u001b[38;5;124m     set datetime = TO_TIMESTAMP((TO_CHAR(date, \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mYYYY-MM-DD\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m) || \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m 12:00:00\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m),\u001b[39m\n\u001b[1;32m      9\u001b[0m \u001b[38;5;124m                         \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mYYYY-MM-DD hh24:mi:ss\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m)::timestamp without time zone;\u001b[39m\u001b[38;5;124m\"\"\"\u001b[39m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m db_eng\u001b[38;5;241m.\u001b[39mconnect() \u001b[38;5;28;01mas\u001b[39;00m conn:\n\u001b[0;32m---> 11\u001b[0m     result \u001b[38;5;241m=\u001b[39m conn\u001b[38;5;241m.\u001b[39mexecute(sql_text(qupdate))\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1306\u001b[0m, in \u001b[0;36mConnection.execute\u001b[0;34m(self, statement, *multiparams, **params)\u001b[0m\n\u001b[1;32m   1302\u001b[0m     util\u001b[38;5;241m.\u001b[39mraise_(\n\u001b[1;32m   1303\u001b[0m         exc\u001b[38;5;241m.\u001b[39mObjectNotExecutableError(statement), replace_context\u001b[38;5;241m=\u001b[39merr\n\u001b[1;32m   1304\u001b[0m     )\n\u001b[1;32m   1305\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 1306\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m meth(\u001b[38;5;28mself\u001b[39m, multiparams, params, _EMPTY_EXECUTION_OPTS)\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/sql/elements.py:332\u001b[0m, in \u001b[0;36mClauseElement._execute_on_connection\u001b[0;34m(self, connection, multiparams, params, execution_options, _force)\u001b[0m\n\u001b[1;32m    328\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_execute_on_connection\u001b[39m(\n\u001b[1;32m    329\u001b[0m     \u001b[38;5;28mself\u001b[39m, connection, multiparams, params, execution_options, _force\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m    330\u001b[0m ):\n\u001b[1;32m    331\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m _force \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msupports_execution:\n\u001b[0;32m--> 332\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m connection\u001b[38;5;241m.\u001b[39m_execute_clauseelement(\n\u001b[1;32m    333\u001b[0m             \u001b[38;5;28mself\u001b[39m, multiparams, params, execution_options\n\u001b[1;32m    334\u001b[0m         )\n\u001b[1;32m    335\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    336\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m exc\u001b[38;5;241m.\u001b[39mObjectNotExecutableError(\u001b[38;5;28mself\u001b[39m)\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1498\u001b[0m, in \u001b[0;36mConnection._execute_clauseelement\u001b[0;34m(self, elem, multiparams, params, execution_options)\u001b[0m\n\u001b[1;32m   1486\u001b[0m compiled_cache \u001b[38;5;241m=\u001b[39m execution_options\u001b[38;5;241m.\u001b[39mget(\n\u001b[1;32m   1487\u001b[0m     \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcompiled_cache\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mengine\u001b[38;5;241m.\u001b[39m_compiled_cache\n\u001b[1;32m   1488\u001b[0m )\n\u001b[1;32m   1490\u001b[0m compiled_sql, extracted_params, cache_hit \u001b[38;5;241m=\u001b[39m elem\u001b[38;5;241m.\u001b[39m_compile_w_cache(\n\u001b[1;32m   1491\u001b[0m     dialect\u001b[38;5;241m=\u001b[39mdialect,\n\u001b[1;32m   1492\u001b[0m     compiled_cache\u001b[38;5;241m=\u001b[39mcompiled_cache,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1496\u001b[0m     linting\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdialect\u001b[38;5;241m.\u001b[39mcompiler_linting \u001b[38;5;241m|\u001b[39m compiler\u001b[38;5;241m.\u001b[39mWARN_LINTING,\n\u001b[1;32m   1497\u001b[0m )\n\u001b[0;32m-> 1498\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_execute_context(\n\u001b[1;32m   1499\u001b[0m     dialect,\n\u001b[1;32m   1500\u001b[0m     dialect\u001b[38;5;241m.\u001b[39mexecution_ctx_cls\u001b[38;5;241m.\u001b[39m_init_compiled,\n\u001b[1;32m   1501\u001b[0m     compiled_sql,\n\u001b[1;32m   1502\u001b[0m     distilled_params,\n\u001b[1;32m   1503\u001b[0m     execution_options,\n\u001b[1;32m   1504\u001b[0m     compiled_sql,\n\u001b[1;32m   1505\u001b[0m     distilled_params,\n\u001b[1;32m   1506\u001b[0m     elem,\n\u001b[1;32m   1507\u001b[0m     extracted_params,\n\u001b[1;32m   1508\u001b[0m     cache_hit\u001b[38;5;241m=\u001b[39mcache_hit,\n\u001b[1;32m   1509\u001b[0m )\n\u001b[1;32m   1510\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m has_events:\n\u001b[1;32m   1511\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdispatch\u001b[38;5;241m.\u001b[39mafter_execute(\n\u001b[1;32m   1512\u001b[0m         \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m   1513\u001b[0m         elem,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1517\u001b[0m         ret,\n\u001b[1;32m   1518\u001b[0m     )\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1862\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1859\u001b[0m             branched\u001b[38;5;241m.\u001b[39mclose()\n\u001b[1;32m   1861\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mBaseException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m-> 1862\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_handle_dbapi_exception(\n\u001b[1;32m   1863\u001b[0m         e, statement, parameters, cursor, context\n\u001b[1;32m   1864\u001b[0m     )\n\u001b[1;32m   1866\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py:2043\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception\u001b[0;34m(self, e, statement, parameters, cursor, context)\u001b[0m\n\u001b[1;32m   2041\u001b[0m     util\u001b[38;5;241m.\u001b[39mraise_(newraise, with_traceback\u001b[38;5;241m=\u001b[39mexc_info[\u001b[38;5;241m2\u001b[39m], from_\u001b[38;5;241m=\u001b[39me)\n\u001b[1;32m   2042\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m should_wrap:\n\u001b[0;32m-> 2043\u001b[0m     util\u001b[38;5;241m.\u001b[39mraise_(\n\u001b[1;32m   2044\u001b[0m         sqlalchemy_exception, with_traceback\u001b[38;5;241m=\u001b[39mexc_info[\u001b[38;5;241m2\u001b[39m], from_\u001b[38;5;241m=\u001b[39me\n\u001b[1;32m   2045\u001b[0m     )\n\u001b[1;32m   2046\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m   2047\u001b[0m     util\u001b[38;5;241m.\u001b[39mraise_(exc_info[\u001b[38;5;241m1\u001b[39m], with_traceback\u001b[38;5;241m=\u001b[39mexc_info[\u001b[38;5;241m2\u001b[39m])\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/util/compat.py:208\u001b[0m, in \u001b[0;36mraise_\u001b[0;34m(***failed resolving arguments***)\u001b[0m\n\u001b[1;32m    205\u001b[0m     exception\u001b[38;5;241m.\u001b[39m__cause__ \u001b[38;5;241m=\u001b[39m replace_context\n\u001b[1;32m    207\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 208\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m exception\n\u001b[1;32m    209\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    210\u001b[0m     \u001b[38;5;66;03m# credit to\u001b[39;00m\n\u001b[1;32m    211\u001b[0m     \u001b[38;5;66;03m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[1;32m    212\u001b[0m     \u001b[38;5;66;03m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[1;32m    213\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/base.py:1819\u001b[0m, in \u001b[0;36mConnection._execute_context\u001b[0;34m(self, dialect, constructor, statement, parameters, execution_options, *args, **kw)\u001b[0m\n\u001b[1;32m   1817\u001b[0m                 \u001b[38;5;28;01mbreak\u001b[39;00m\n\u001b[1;32m   1818\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m evt_handled:\n\u001b[0;32m-> 1819\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdialect\u001b[38;5;241m.\u001b[39mdo_execute(\n\u001b[1;32m   1820\u001b[0m             cursor, statement, parameters, context\n\u001b[1;32m   1821\u001b[0m         )\n\u001b[1;32m   1823\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_has_events \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mengine\u001b[38;5;241m.\u001b[39m_has_events:\n\u001b[1;32m   1824\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mdispatch\u001b[38;5;241m.\u001b[39mafter_cursor_execute(\n\u001b[1;32m   1825\u001b[0m         \u001b[38;5;28mself\u001b[39m,\n\u001b[1;32m   1826\u001b[0m         cursor,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1830\u001b[0m         context\u001b[38;5;241m.\u001b[39mexecutemany,\n\u001b[1;32m   1831\u001b[0m     )\n",
      "File \u001b[0;32m~/anaconda3/lib/python3.11/site-packages/sqlalchemy/engine/default.py:732\u001b[0m, in \u001b[0;36mDefaultDialect.do_execute\u001b[0;34m(self, cursor, statement, parameters, context)\u001b[0m\n\u001b[1;32m    731\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdo_execute\u001b[39m(\u001b[38;5;28mself\u001b[39m, cursor, statement, parameters, context\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[0;32m--> 732\u001b[0m     cursor\u001b[38;5;241m.\u001b[39mexecute(statement, parameters)\n",
      "\u001b[0;31mProgrammingError\u001b[0m: (psycopg2.errors.DuplicateColumn) column \"datetime\" of relation \"reviews\" already exists\n\n[SQL: \n alter table reviews\n     add column datetime timestamp;\n     \n]\n(Background on this error at: https://sqlalche.me/e/14/f405)"
     ]
    }
   ],
   "source": [
    "#1A SETUP FOR TEST 1\n",
    "\n",
    "qupdate = \"\"\"\n",
    " alter table reviews\n",
    "     add column datetime timestamp;\n",
    "\"\"\"\n",
    "\n",
    "qimport = \"\"\"update reviews\n",
    "     set datetime = TO_TIMESTAMP((TO_CHAR(date, 'YYYY-MM-DD') || ' 12:00:00'),\n",
    "                         'YYYY-MM-DD hh24:mi:ss')::timestamp without time zone;\"\"\"\n",
    "\n",
    "with db_eng.connect() as conn:\n",
    "    result = conn.execute(sql_text(qupdate))\n",
    "    result = conn.execute(sql_text(qimport))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e2ca586",
   "metadata": {},
   "outputs": [],
   "source": [
    "#1B SETUP for TEST 1, find number of \n",
    "q_yearinfo = \"\"\"\n",
    " select COUNT(*)\n",
    " FROM reviews\n",
    " \n",
    " SORT BY date\n",
    "     \n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "df4bf26a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Processing spec:  [] \n",
      "\n",
      "\n",
      "Index name:datetime_in_reviews\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "DROP INDEX IF EXISTS datetime_in_reviews;\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the drop for ['datetime', 'reviews'] the indexes on table \"reviews\" are: \n",
      "[('new_york_city', 'reviews', 'date_in_reviews', None, 'CREATE INDEX date_in_reviews ON new_york_city.reviews USING btree (date)')]\n",
      "\n",
      "Index name:id_in_listings\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "DROP INDEX IF EXISTS id_in_listings;\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the drop for ['id', 'listings'] the indexes on table \"listings\" are: \n",
      "[]\n",
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "Processing spec:  [['datetime', 'reviews']] \n",
      "\n",
      "\n",
      "Index name:id_in_listings\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "DROP INDEX IF EXISTS id_in_listings;\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the drop for ['id', 'listings'] the indexes on table \"listings\" are: \n",
      "[]\n",
      "\n",
      "Index name:datetime_in_reviews\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "CREATE INDEX IF NOT EXISTS datetime_in_reviews\n",
      "ON reviews(datetime);\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the add for ['datetime', 'reviews'] the indexes on table \"reviews\" are: \n",
      "[('new_york_city', 'reviews', 'date_in_reviews', None, 'CREATE INDEX date_in_reviews ON new_york_city.reviews USING btree (date)'), ('new_york_city', 'reviews', 'datetime_in_reviews', None, 'CREATE INDEX datetime_in_reviews ON new_york_city.reviews USING btree (datetime)')]\n",
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "Processing spec:  [['id', 'listings']] \n",
      "\n",
      "\n",
      "Index name:datetime_in_reviews\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "DROP INDEX IF EXISTS datetime_in_reviews;\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the drop for ['datetime', 'reviews'] the indexes on table \"reviews\" are: \n",
      "[('new_york_city', 'reviews', 'date_in_reviews', None, 'CREATE INDEX date_in_reviews ON new_york_city.reviews USING btree (date)')]\n",
      "\n",
      "Index name:id_in_listings\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "CREATE INDEX IF NOT EXISTS id_in_listings\n",
      "ON listings(id);\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the add for ['id', 'listings'] the indexes on table \"listings\" are: \n",
      "[('new_york_city', 'listings', 'id_in_listings', None, 'CREATE INDEX id_in_listings ON new_york_city.listings USING btree (id)')]\n",
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "Processing spec:  [['datetime', 'reviews'], ['id', 'listings']] \n",
      "\n",
      "\n",
      "Index name:datetime_in_reviews\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "CREATE INDEX IF NOT EXISTS datetime_in_reviews\n",
      "ON reviews(datetime);\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the add for ['datetime', 'reviews'] the indexes on table \"reviews\" are: \n",
      "[('new_york_city', 'reviews', 'date_in_reviews', None, 'CREATE INDEX date_in_reviews ON new_york_city.reviews USING btree (date)'), ('new_york_city', 'reviews', 'datetime_in_reviews', None, 'CREATE INDEX datetime_in_reviews ON new_york_city.reviews USING btree (datetime)')]\n",
      "\n",
      "Index name:id_in_listings\n",
      "QUERY TO EXECUTE:\n",
      "BEGIN TRANSACTION;\n",
      "CREATE INDEX IF NOT EXISTS id_in_listings\n",
      "ON listings(id);\n",
      " END TRANSACTION;\n",
      "\n",
      "\n",
      "After doing the add for ['id', 'listings'] the indexes on table \"listings\" are: \n",
      "[('new_york_city', 'listings', 'id_in_listings', None, 'CREATE INDEX id_in_listings ON new_york_city.listings USING btree (id)')]\n",
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n"
     ]
    }
   ],
   "source": [
    "#1 RUN TEST \n",
    "all_indexes = [['datetime','reviews'], ['id','listings']]\n",
    "perf_summary = util.fetch_perf_data('perf_summary.json')\n",
    "\n",
    "count = 5\n",
    "# store all of the index combinations to test\n",
    "specs = [[],[['datetime','reviews']],[['id','listings']],[['datetime','reviews'],['id','listings']]] \n",
    "for spec in specs:\n",
    "    \n",
    "    # set up the correct indices\n",
    "    print('Processing spec: ', str(spec), '\\n')\n",
    "    for index in all_indexes:\n",
    "        if index not in spec:\n",
    "            mod_index = util.add_drop_index(db_eng, 'drop', index[0], index[1])\n",
    "            print('\\nAfter doing the drop for', str(index), 'the indexes on table \"' + index[1] + '\" are: ')\n",
    "            print(mod_index)\n",
    "\n",
    "    for index in spec:\n",
    "        mod_index = util.add_drop_index(db_eng, 'add', index[0], index[1])\n",
    "        print('\\nAfter doing the add for', str(index), 'the indexes on table \"' + index[1] + '\" are: ')\n",
    "        print(mod_index)\n",
    "    \n",
    "\n",
    "    for i in range(0, count):\n",
    "        print(i)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
